version: '3.9'

services:

  burgerworld-db:
    container_name: burgerworld-db
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: burgerworld
    ports:
      - "3308:3306"
    networks:
      - burgerworld-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  burgerworld:
    container_name: burgerworld
    image: burgerworld:latest
    build:
      context: ""
      dockerfile: BurgerworldDockerFile
    ports:
      - "8080:8080"
    networks:
      - burgerworld-net
    depends_on:
      burgerworld-db:
        condition: service_healthy

networks:
  burgerworld-net:
    driver: bridge